DROP TABLES IF EXISTS `Scores`;
DROP TABLES IF EXISTS `Exams`;
DROP TABLES IF EXISTS `Exams_results`;
DROP TABLES IF EXISTS `Teacher`;
DROP TABLES IF EXISTS `Graduants`;
DROP TABLES IF EXISTS `Faculty`;